authorName: hotaekhan
experimentName: prac
trialConcurrency: 1
maxExecDuration: 1d
maxTrialNum: 100
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Medianstop
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
    #epoch_num: 20
    #threshold: 0.9
    start_step: 5
trial:
  command: python train_nni.py --config=configs/config.yaml
  codeDir: ../
  gpuNum: 1
localConfig:
  useActiveGpu: True
